package pages;

import org.junit.Assert;
import org.openqa.selenium.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import utils.ConfigReader;
import utils.ElementUtils;
import utils.ExcelUtils;
import utils.TestDataGenerator;

import java.io.IOException;
import java.time.Duration;
import java.util.*;
import java.util.stream.Collectors;



public class HWMastersPage extends BasePage {

    public HWMastersPage(WebDriver driver) {
        super(driver);
    }

    public static final By CRITICALITY = By.id("ctl00_ContentPlaceHolder1_RadWinHWCriticality_C_radtxtHWCriticality");
    public static final By SEARCH_CRITICALITY = By.cssSelector("[alt='Filter HWCriticality column']");
    public static final By DELETE_RECORD = By.id("ctl00_ContentPlaceHolder1_grdHWCriticality_ctl00_ctl04_ImageButton2");
    public static final By CLICK_CRITICALITY = By.id("ctl00_ContentPlaceHolder1_grdHWCriticality_ctl00__0");
    public static final By CHANGE_STATUS_CRITICALITY = By.xpath("//input[@id='chkCriticalActive']");
    public static final By FIELD_NAME_INPUT = By.xpath("//input[@id='ctl00_ContentPlaceHolder1_RadWinChecklistField_C_FieldsName']");
    public static final By DATA_TYPE_DROPDOWN = By.xpath("//input[@id='ctl00_ContentPlaceHolder1_RadWinChecklistField_C_DatatypeDrop_Input']");
    public static final By dropDownProperty = By.id("ctl00_ContentPlaceHolder1_ddlProperty_Input");
    public static final By dropDownZone = By.id("ctl00_ContentPlaceHolder1_ddlZone_Input");
    public static final By dropDownSubZone = By.id("ctl00_ContentPlaceHolder1_ddlSubzone_Input");
    public static final By dropDownBaseUnit = By.id("ctl00_ContentPlaceHolder1_ddlBaseUnit_Input");

    public void enterCriticality(String criticality) {
        utils.typeText(CRITICALITY, criticality);
    }

    public void verifyCriticality(String expectedTitle) {
        utils.typeText(SEARCH_CRITICALITY, expectedTitle + Keys.ENTER);
        By locator = By.cssSelector(String.format("[id=ctl00_ContentPlaceHolder1_grdHWCriticality_ctl00__0] td[title='%s']", expectedTitle));
        utils.isElementVisible(locator);
    }

    public void deleteRecord() {
        utils.click(DELETE_RECORD);
        Alert alert = driver.switchTo().alert();
        alert.accept();
    }

    public void verifyDeletedCriticality(String expectedTitle) {
        utils.typeText(SEARCH_CRITICALITY, expectedTitle + Keys.ENTER);
        By locator = By.xpath(("//tr[@class=\"rgNoRecords\"]//div[text()='No records to display.']"));
        utils.isElementVisible(locator);
    }

    public void clickOnCriticality() {
        utils.click(CLICK_CRITICALITY);

    }

    public void verifyUsedCriticality(String expectedTitle) {
        utils.typeText(SEARCH_CRITICALITY, expectedTitle + Keys.ENTER);
        By usedCriticality = By.xpath(("//input[@class='disable-hover']"));
        if (utils.isElementVisible(usedCriticality)) {
            utils.click(DELETE_RECORD);
            Alert alert = driver.switchTo().alert();
            alert.accept();
            System.out.println("Record Deleted Successfully");
        } else {
            System.out.println("This record is Already used, can't delete");
        }
    }

    public void verifyStatus() {
        By activeIcon = By.xpath("//span[contains(@class, 'circle')]");
        if (utils.isElementVisible(activeIcon)) {
            System.out.println("This record is Active");
        } else {
            System.out.println("This record is Inactive");
        }
    }

    public void changeCriticalityStatus() {
        utils.click(CHANGE_STATUS_CRITICALITY);

    }

    public void createField(String fieldName, String dataType) {
        utils.typeText(FIELD_NAME_INPUT, fieldName);
        utils.selectDropdownByText(DATA_TYPE_DROPDOWN, dataType);
    }

    public void clickOnTabByTitle(String tabTitle) {
        try {
            By locator = By.xpath(String.format("//div[@class='labels-container']//a[text()='%s']", tabTitle));
            utils.click(locator);
            System.out.println("Clicked on the tab: " + tabTitle);
        } catch (Exception e) {
            System.out.println("Failed to click on the tab: " + tabTitle);
            throw e;
        }
    }

    public void verifyAutogeneratedHWNo(String elementId) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));


        WebElement autoField = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(elementId)));

        String readOnlyAttr = autoField.getAttribute("readonly");
        boolean isEnabled = autoField.isEnabled();
        Assert.assertTrue("FAIL: HW Number " + elementId + " is NOT in read-only mode.", readOnlyAttr != null || !isEnabled);
        String fieldValue = autoField.getAttribute("value");
        if (fieldValue == null || fieldValue.trim().isEmpty()) {
            Assert.fail("ERROR: Value not available in the autogenerated HW Number: " + elementId);
        } else {
            System.out.println("SUCCESS: Autogenerated HW Number found: " + fieldValue);
        }
    }

    public void verifyAutogeneratedRequestedOn(String elementId) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));


        WebElement autoField = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(elementId)));

        String readOnlyAttr = autoField.getAttribute("readonly");
        boolean isEnabled = autoField.isEnabled();
        Assert.assertTrue("FAIL: Requested On " + elementId + " is NOT in read-only mode.", readOnlyAttr != null || !isEnabled);
        String fieldValue = autoField.getAttribute("value");
        if (fieldValue == null || fieldValue.trim().isEmpty()) {
            Assert.fail("ERROR: Value not available in the autogenerated Requested On: " + elementId);
        } else {
            System.out.println("SUCCESS: Autogenerated Requested On found: " + fieldValue);
        }
    }

//    public void verifyAutogeneratedInitiatedBy(String elementId) {
//        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//
//
//        WebElement autoField = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(elementId)));
//
//        String readOnlyAttr = autoField.getAttribute("readonly");
//        boolean isEnabled = autoField.isEnabled();
//        Assert.assertTrue("FAIL: Initiated By " + elementId + " is NOT in read-only mode.", readOnlyAttr != null || !isEnabled);
//        String fieldValue = autoField.getAttribute("value");
//        if (fieldValue == null || fieldValue.trim().isEmpty()) {
//            Assert.fail("ERROR: Value not available in the autogenerated Initiated By: " + elementId);
//        } else {
//            System.out.println("SUCCESS: Autogenerated Initiated By found: " + fieldValue);
//        }
//    }

    static Map<String, By> dropdownFieldMap = new HashMap<>();
    static Map<String, By> dropdownOptionsMap = new HashMap<>();

    public void initDropdowns() {

        dropdownFieldMap.put("Criticality", By.id("ctl00_ContentPlaceHolder1_ddlCriticality_Input"));
        dropdownOptionsMap.put("Criticality", By.cssSelector("[id*='ddlCriticality_DropDown'] li"));

        dropdownFieldMap.put("High Risk Activity Type", By.id("ctl00_ContentPlaceHolder1_ddlHWType_Input"));
        dropdownOptionsMap.put("High Risk Activity Type", By.cssSelector("[id*='ddlHWType_DropDown'] li"));

        dropdownFieldMap.put("Property Owner / Customer", By.id("ctl00_ContentPlaceHolder1_ddlCustomer_Input"));
        dropdownOptionsMap.put("Property Owner / Customer", By.cssSelector("[id*='ddlCustomer_DropDown'] li"));

        dropdownFieldMap.put("Property (Contract)", By.id("ctl00_ContentPlaceHolder1_ddlContract_Input"));
        dropdownOptionsMap.put("Property (Contract)", By.cssSelector("[id*='ddlContract_DropDown'] li"));
    }

//    public static void selectRandomDropdownValue(String dropdownName) {
//        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
//
//        By fieldLocator = dropdownFieldMap.get(dropdownName);
//        By optionsLocator = dropdownOptionsMap.get(dropdownName);
//
//        for (int attempt = 0; attempt < 3; attempt++) {
//            try {
//                waitForAjaxToComplete();
//
//                WebElement dropdown = wait.until(ExpectedConditions.elementToBeClickable(fieldLocator));
//                dropdown.click();
//
//                wait.until(ExpectedConditions.visibilityOfElementLocated(optionsLocator));
//
//                List<WebElement> options = driver.findElements(optionsLocator);
//
//                List<WebElement> validOptions = options.stream()
//                        .filter(e -> e.isDisplayed() && e.isEnabled())
//                        .collect(Collectors.toList());
//
//                int index = new Random().nextInt(validOptions.size());
//
//                options = driver.findElements(optionsLocator); // re-fetch
//                options.get(index).click();
//
//                waitForAjaxToComplete();
//                break;
//
//            } catch (StaleElementReferenceException e) {
//                if (attempt == 2) throw e;
//            }
//        }
    }

    //ElementUtils elementUtils = new ElementUtils();

//    public static void waitForAjaxToComplete() {
//        ElementUtils.waitForAjaxToComplete(driver);
//    }
//}


//    public String selectRandomLevel() {
//        Select select = new Select(driver.findElement(dropDownLevel));
//        List<WebElement> options = select.getOptions();
//
//        // Pick a random option (skipping the first "Select..." placeholder)
//        int index = new Random().nextInt(options.size() - 1) + 1;
//        String levelName = options.get(index).getText();
//        select.selectByIndex(index);
//        return levelName;
//    }
//    public void selectOption(By locator, String text) {
//        new Select(driver.findElement(locator)).selectByVisibleText(text);
//    }


