package stepDefinitions;

import io.cucumber.java.en.And;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import pages.AuditInspections;
import pages.AuditManagement;
import pages.TrainingManagementMastersPage;
import utils.DriverFactory;
import utils.HelperUtils;
import utils.TestDataModel;

import java.util.Map;

public class AuditInspectionsStep {
    private final WebDriver driver = DriverFactory.getDriver();
    AuditInspections auditInspections = new AuditInspections(driver);
    private final HelperUtils helperUtils = new HelperUtils(driver);
    static TestDataModel testData = new TestDataModel();

    @Then("User checks the Initiated By {string} should be autogenerated and read-only")
    public void verify_field_InitiatedBy(String fieldName) {
        AuditInspections.verifyAutogeneratedInitiatedBy(fieldName);
    }
    @Then("User verify the Scheduled name field")
    public void verify_the_Schedule_name_field_() {
        AuditInspections.getScheduleName();
    }
    @When("User select the {string} Audit Master Category dropdown")
    public void user_select_the_Audit_Master_Category_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditMasterCatDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditMasterCat(value);
    }
    @When("User select the {string} Audit Category dropdown")
    public void user_select_the_Audit_Category_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditCategoryDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditCategory(value);
    }
    @Then("User verify the Schedule Name details")
    public void User_verify_the_Schedule_Name_details() {
        AuditInspections.ValidateScheduleNamedetails();
    }
    @Then("User selects Check All for Applicable Zones")
    public void User_selects_Check_All_Applicable_Zones() {
        AuditInspections.CheckApplicableZones();
    }

    @When("User select the {string} Client dropdown")
    public void user_select_the_Client_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomClientDropdown();
            return;
        }
        AuditInspections.searchAndSelectClient(value);
    }
    @When("User select the {string} Client Category dropdown")
    public void user_select_the_Client_Category_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomClientContractDropdown();
            return;
        }
        AuditInspections.searchAndSelectClientContract(value);
    }
    @When("User select the {string} Property dropdown")
    public void user_select_the_Property_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomPropertyDropdown();
            return;
        }
        AuditInspections.searchAndSelectProperty(value);
    }
    @When("User select the {string} Primary Auditee dropdown")
    public void user_select_the_Primary_Auditee_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomPrimaryAuditeeDropdown();
            return;
        }
        AuditInspections.searchAndSelectPrimaryAuditee(value);
    }
    @When("User select the {string} Schedule Start Date")
    public void user_select_the_Schedule_Start_Date(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){
            AuditInspections.SelectTodayAsStartDate();
            return;
        }
        AuditInspections.enterScheduleStartDate(value);
    }
    @When("User select the {string} Schedule End Date")
    public void user_select_the_Schedule_End_Date(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){
            AuditInspections.SelectRandomEndDate();
            return;
        }
        AuditInspections.enterScheduleEndDate(value);
    }
    @When("User select the {string} Frequency dropdown")
    public void user_select_the_Frequency_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.selectFrequencyBasedOnDates();
            return;
        }
        AuditInspections.searchAndSelectFrequency(value);
    }
    @When("User select the {string} Audit Company Type dropdown")
    public void user_select_the_Audit_Company_Type_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditCompanyTypeDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditCompanyType(value);
    }
    @When("User select the {string} Auditor Designation dropdown")
    public void user_select_the_Auditor_Designation_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditorDesignationDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditorDesignation(value);
    }
    @When("User clicking on Save Button in Schedules")
    public void user_Clicking_on_Save_Button_in_Schedules() {
        AuditInspections.ClickSaveButtoninSchedule();
    }
    @When("user verify the chars and max len as {int} for Audit Category")
    public void user_verify_chars_len_AuditCategory(int maxLen) {
        helperUtils.verifyMinAndMaxLength(By.xpath("//input[@id='radTxtAuditCategory']"),maxLen, null);
    }
    @And("User clicks on Save button For Schedule InLine Error")
    public void user_clicks_on_save_button_for_in_line_error() {
        AuditInspections.clickSaveButtonInSchedulelineError();
    }
    @When("user verify the chars and max len as {int} for Schedule Name")
    public void user_verify_chars_len_ScheduleName(int maxLen) {
        helperUtils.verifyMinAndMaxLength(By.xpath("//input[@id='ctl00_ContentPlaceHolder1_RadTxt_AsheCat']"),maxLen, null);
    }
    @Then("User verifies added Audit Schedule details in table")
    public void user_verifies_added_Audit_Schedule_details_in_table() throws InterruptedException {
        AuditInspections.verifySchedule();
        AuditInspections.verifyScheduleName();
        AuditInspections.verifyAuditCategory();
        AuditInspections.verifyProperty();
        AuditInspections.verifyPrimaryAuditee();
    }
    @When("User select the {string} Schedule No record to edit")
    public void user_select_the_Schedule_No_record_to_edit(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){AuditInspections.getScheduleNoEdit();
            return;
        }
        AuditInspections.searchAndSelectScheduleNoEdit(value);
    }
    @When("User select the Schedule No record to Delete")
    public void user_select_the_Schedule_No_record_to_Delete() throws InterruptedException {
        AuditInspections.getScheduleNoDelete();
    }
    @Then("User clicks on available audit to delete")
    public void user_clicks_on_available_audit_to_delete() {
        AuditInspections.clickDeleteButtonA();
    }
    @When("User verify if the Audit Schedule record is deleted")
    public void user_verify_Audit_Schedule_record_deleted() {
        AuditInspections.verifyNoScheduleRecordsPresent();
    }
    @When("user verify the chars and max len as {int} for Audit Name")
    public void user_verify_chars_len_AuditName(int maxLen) {
        helperUtils.verifyMinAndMaxLength(By.xpath("//input[@id='ctl00_ContentPlaceHolder1_txtAuditName']"),maxLen, null);
    }
    @Then("user verify the inline error message {string} on Audit Inspections")
    public void verify_inline_error_msg_in_Audit_Inspections(String error){
        By errorPath = By.xpath("(//span[contains(@id, 'ContentPlaceHolder1') and text()='"+error+"'])[1]");
        helperUtils.verifyInlineErrorMessage(errorPath, error);
    }
    @When("User select the {string} UnSchedule Audit Master Category dropdown")
    public void user_select_the_UnSchedule_Audit_Master_Category_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomUSAuditMasterCatDropdown();
            return;
        }
        AuditInspections.searchAndSelectUSAuditMasterCat(value);
    }
    @When("User select the {string} UnSchedule Audit Category dropdown")
    public void user_select_the_UnSchedule_Audit_Category_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomUSAuditCategoryDropdown();
            return;
        }
        AuditInspections.searchAndSelectUSAuditCategory(value);
    }
    @Then("User verify the Audit Name details")
    public void User_verify_the_Audit_Name_details() {
        AuditInspections.ValidateAuditNamedetails();
    }
    @When("User select the {string} US Client dropdown")
    public void user_select_the_US_Client_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomUSClientDropdown();
            return;
        }
        AuditInspections.searchAndSelectUSClient(value);
    }
    @When("User select the {string} US Property dropdown")
    public void user_select_the_US_Property_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomUSPropertyDropdown();
            return;
        }
        AuditInspections.searchAndSelectUSProperty(value);
    }
    @When("User select the {string} Auditor Company dropdown")
    public void user_select_the_Auditor_Company_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditorCompanyDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditorCompany(value);
    }
    @When("User select the {string} Auditee dropdown")
    public void user_select_the_Auditee_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditeeDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditee(value);
    }
    @When("User select the {string} Auditee StaffName dropdown")
    public void user_select_the_Auditee_StaffName_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditeeStaffNameDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditeeStaffName(value);
    }
    @When("User select the {string} Auditor dropdown")
    public void user_select_the_Auditor_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomAuditorDropdown();
            return;
        }
        AuditInspections.searchAndSelectAuditor(value);
    }
    @Then("User Select the page size {int}")
    public static void user_waits_for_seconds(int pages) {
        AuditInspections.PagesizeSelection(pages);
    }
    @Then("User verifies added UnSchedule Audit details in table")
    public void user_verifies_added_UnSchedule_Audit_details_in_table() throws InterruptedException {
        AuditInspections.verifyAuditNO();
        AuditInspections.verifyAuditType();
        AuditInspections.verifyUSScheduleName();
        AuditInspections.verifyScheduleDate();
        AuditInspections.verifyUSAuditCategory();
        AuditInspections.verifyUSProperty();
        AuditInspections.verifyUSAuditee();
        AuditInspections.verifyUSAuditorCompany();
        AuditInspections.verifyUSAuditor();
    }
    @When("User select the US and Schedule Audit No record to Delete")
    public void user_select_the_US_Schedule_Audit_No_record_to_Delete() throws InterruptedException {
        AuditInspections.getScheduleAuditNoDelete();
    }
    @Then("User clicks on Assigned audits to delete")
    public void user_clicks_on_Assigned_audits_to_delete() {
        AuditInspections.DeleteAssignedAudit();
    }
    @When("User verify if the Deleted Assigned record is deleted")
    public void user_verify_Deleted_Assigned_record_deleted() {
        AuditInspections.verifyDeletedAssignedRecordsPresent();
    }
    @When("User select the US and Schedule Audit No record to Reschedule")
    public void user_select_the_US_Schedule_Audit_No_record_to_Reschedule() throws InterruptedException {
        AuditInspections.getScheduleAuditNoReschedule();
    }
    @Then("User clicks on Assigned audits to Reschedule")
    public void user_clicks_on_Assigned_audits_to_Reschedule() {
        AuditInspections.RescheduleAssignedAudit();
    }
    @When("User verify if the Rescheduled date Assigned record is changed")
    public void user_verify_Rescheduled_date_Assigned_record_Changed() {
        AuditInspections.verifyRescheduleddateisChanged();
    }
    @When("User select the Pending Assignments and Schedule Audit No record to Assign")
    public void user_select_the_Pending_Assignments_Schedule_Audit_No_record_to_Assign() throws InterruptedException {
        AuditInspections.getScheduleAuditNoAssign();
    }
    @Then("User clicks on Schedule audits to Assign")
    public void user_clicks_on_Schedule_audits_Assign() {
        AuditInspections.AssignScheduledAudit();
    }
    @Then("User get All Assign Audit details")
    public void user_get_All_Assign_Audit_details() {
        AuditInspections.getAllAsignAuditdetails();
    }
    @Then("User verifies Assigned details in Assigned Audits in table")
    public void user_verifies_Assigned_details_in_Assigned_Audits_in_table() throws InterruptedException {
        AuditInspections.verifyAuditNO();
        AuditInspections.verifyUSScheduleName();
        AuditInspections.verifyUSAuditee();
        AuditInspections.verifyUSAuditorCompany();
        AuditInspections.verifyUSAuditor();
    }
    @When("User clicks on {string} tab in Open Audits by Status")
    public void user_clicks_OpenAudits_tab_in_open_Audits(String tabName) throws InterruptedException {
        AuditInspections.clickAuditStatusTab(tabName);
    }
    @And("User select the OA and {string} Unassigned Schedule No record to Delete")
    public void user_select_the_OA_and_Unassigned_Schedule_No_record_to_Delete(String gridName) throws InterruptedException {
        AuditInspections.getUnAssignedScheduleNoDelete(gridName);
    }

    @Then("User Select the page size {int} for {string} tab")
    public static void user_select_pages(int pages, String gridName) {
        AuditInspections.PagesizetabSelection(pages, gridName);
    }
    @When("User verify if the UnAssigned record is deleted")
    public void user_verify_UnAssigned_record_deleted() {
        AuditInspections.verifyDeletedUnAssignedRecordsPresent();
    }
    @When("User get the auditee details from table")
    public void user_get_the_auditee_details_from_table() {
        AuditInspections.getauditdetailsfromtable();
    }
    @Then("User clicks on UnAssigned Schedule audits to open")
    public void user_clicks_on_UnAssigned_Schedule_audits_open() {
        AuditInspections.openUnAssignedAudit();
    }
    @Then("User verifies UnAssigned Schedule Audit Schedule details in table")
    public void user_verifies_UnAssigned_Schedule_details_in_table() throws InterruptedException {
        AuditInspections.verifyUNScheduleNo();
        AuditInspections.verifyUNScheduleName();
        AuditInspections.verifyUNAuditCategory();
        AuditInspections.verifyUNProperty();
        AuditInspections.verifyUNPrimaryAuditee();
    }
    @And("User select the OA and {string} Schedule No record to Delete")
    public void user_select_the_OA_and_Schedule_No_record_to_Delete(String gridName) throws InterruptedException {
        AuditInspections.SelectRandomAuditfromTable(gridName);
    }
    @When("User get the {string} auditee details from table")
    public void user_get_the_Overdue_auditee_details_from_table(String gridName) {
        AuditInspections.getOverdueauditdetailsfromtable(gridName);
    }
    @Then("User clicks on {string} audit to Transfer")
    public void user_clicks_on_available_audit_to_Transfer(String gridName) {
        AuditInspections.clickingTransfer(gridName);
    }
    @And("User select the Tranfer Auditor dropdown")
    public void User_select_the_Tranfer_Auditor_dropdown() {
        AuditInspections.getTranferRandomAuditorComapnyDropdown();
        AuditInspections.getTranferRandomAuditorDropdown();
    }
    @And("User select the Reason dropdown and Remarks Text Save Tranfer")
    public void User_select_the_Reason_dropdown_and_Remarks_Text_Save() {
        AuditInspections.getRandomReasonDropdown();
        AuditInspections.enterRandomRemarksText();
        AuditInspections.clickingonTransferSave();
    }
    @Then("User verifies {string} Tranfer Audit Schedule details in table")
    public void user_verifies_UnAssigned_Tranfer_Schedule_in_table(String gridName) throws InterruptedException {
        AuditInspections.verifyUNAuditNo(gridName);
    }
    @When("User verify if the {string} record is deleted")
    public void user_verify_UnAssigned_record_deleted(String gridName) {
        AuditInspections.verifyDeletedAuditRecordsPresent(gridName);
    }
    @Then("User enter Audit Cancel details")
    public void User_enter_Audit_Cancel_details() {
        AuditInspections.auditCanceldetails();
    }
    @Then("User clicks on {string} Schedule audits to open")
    public void user_clicks_on_OverDue_Schedule_audits_open(String gridName) {
        AuditInspections.openOverDueAudit(gridName);
    }
    @Then("User verifies OverDue Schedule Audit Schedule details in table")
    public void user_verifies_OverDue_Schedule_details_in_table() throws InterruptedException {
        AuditInspections.verifyODAuditStatus();
        AuditInspections.verifyODMasterCategoryName();
        AuditInspections.verifyODAuditName();
        AuditInspections.verifyODPropertyName();
        AuditInspections.verifyODAuditorName();
//        AuditInspections.verifyODAuditee();
    }
    @And("User clicks on first available audit to open")
    public void user_clicks_on_available_audit_to_Open() {
        AuditInspections.getInProgressfirstRecord();
    }
    @When("User select the {string} ACS Audit Master Category dropdown")
    public void user_select_the_ACS_Audit_Master_Category_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){
            AuditInspections.getRandomAMCDropdown();
            return;
        }
        AuditInspections.searchAndSelectAMC(value);
    }
    @And("User Enters ACS Audit Category Name")
    public void user_enters_audit_category_name() {
        AuditInspections.enterAuditCategoryName();
    }
    @When("User select the {string} ACS Enforcing Authority dropdown")
    public void user_select_the_ACS_Enforcing_Authority_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomACSEAuthorityinDropdown();
            return;
        }
        AuditInspections.searchAndSelectACSEnforcingAuthority(value);
    }
    @When("User select the {string} ACS Industry Standard Description dropdown")
    public void user_select_the_ACS_Industry_Standard_Description_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomACSIStandardDescDropdown();
            return;
        }
        AuditInspections.searchAndSelectACSIStandardDesc(value);
    }
    @When("User select the {string} ACS Legal Requirements dropdown")
    public void user_select_the_ACS_Legal_Requirements_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomACSLegalRequireDropdown();
            return;
        }
        AuditInspections.searchAndSelectACSLegalRequire(value);
    }
    @And("User Enters Sampling Location and Asset Percentage")
    public void user_enters_Sampling_Location_Asset_Percentage() {
        AuditInspections.enterrandomLocationSampling();
        AuditInspections.enterrandomAssetSampling();
    }
    @When("User select the {string} ACS Work Order dropdown")
    public void user_select_the_ACS_Work_Order_Dropdown(String value) throws InterruptedException {
        if(value == null || value.isEmpty()){ AuditInspections.getRandomACSWorkOrderDropdown();
            return;
        }
        AuditInspections.searchAndSelectACSWorkOrder(value);
    }
    @And("User checks the Active check box in Create ACS")
    public void user_checks_the_Active_check_box_in_Create_ACS() {
        AuditInspections.checkedEnforceSampling();
        AuditInspections.checkedPredefined();
        AuditInspections.checkedQuesBank();
        AuditInspections.checkedIssueBased();
    }
    @Then("User verifies Audit Category Setup details in table")
    public void user_verifies_Audit_Category_Setup_details_in_table() throws InterruptedException {
        AuditInspections.verifyAMCandACN();
        AuditInspections.verifyEnforcingAuth();
        AuditInspections.verifyIndusStandDesc();
        AuditInspections.verifyLegalReq();
        AuditInspections.verifyAssetLocationSample();
        AuditInspections.verifyWorkOrder();
        AuditInspections.verifyCheckboxValidation();
    }
    @Then("User clicks on First Created Audit to open")
    public void user_clicks_on_First_Created_Audit_open() {
        AuditInspections.openFirstCreatedAudit();
    }
    @And("User clicks on Add Question Category")
    public void user_clicks_on_Add_Question_Category() {
        AuditInspections.addQuestionCategory();
    }
    @And("User clicks on Add Question SubCategory")
    public void user_clicks_on_Add_Question_SubCategory() {
        AuditInspections.addQuestionSubCategory();
    }
    @And("User clicks on Add Question")
    public void user_clicks_on_Add_Question() {
        AuditInspections.addQuestion();
    }











}
