package stepDefinitions;

import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import pages.BasePage;
import pages.HWMastersPage;
import pages.TrainingManagementMastersPage;
import utils.DriverFactory;
import utils.ElementUtils;
import utils.HelperUtils;
import utils.TestDataGenerator;


import java.time.Duration;
import java.util.List;

public class HWMastersSteps {
    public static String generateCriticality;
    private final WebDriver driver = DriverFactory.getDriver();
    TestDataGenerator dataGen = new TestDataGenerator();
    HWMastersPage tmp = new HWMastersPage(driver);
    HelperUtils helperUtils = new HelperUtils(driver);
    ElementUtils elementUtils = new ElementUtils(driver);
    String selectedLevel;

    @Then("user fills up the criticality")
    public void userFillsUpTheCriticality() {
        generateCriticality = dataGen.generateCriticality();
        tmp.enterCriticality(generateCriticality);
    }

    @Then("User verifies if the criticality is created or updated")
    public void user_verify_criticality_creation() {
        tmp.verifyCriticality(generateCriticality);
    }

    @Then("User deletes the added record")
    public void user_deletes_the_added_record() {
        tmp.deleteRecord();
    }

    @Then("User verifies if the criticality is deleted")
    public void user_verify_deleted_criticality() {
        tmp.verifyDeletedCriticality(generateCriticality);
    }

    @When("User clicks on the criticality record")
    public void user_clicks_on_the_criticality_record() {
        tmp.clickOnCriticality();
    }

    @When("user verifies the chars min len as {int} and max len as {int} on High Risk Criticality")
    public void user_verify_chars_len_High_Risk_Criticality(int minLen, int maxLen) {
        helperUtils.verifyMinAndMaxLength(By.id("ctl00_ContentPlaceHolder1_RadWinHWCriticality_C_radtxtHWCriticality"), maxLen, minLen);
    }

    @When("user verifies the inline error message {string} on High Risk Criticality")
    public void userVerifyInlineErrorMessageOnHighRiskCriticality(String expectedErrorMessage) {
        By criticalityErrorLocator = By.xpath("//span[@id='ctl00_ContentPlaceHolder1_RadWinHWCriticality_C_rfvHWCriticality']");
        helperUtils.verifyInlineErrorMessage(criticalityErrorLocator, expectedErrorMessage);
    }

    @Then("User attempts to delete the record and verifies the usage status")
    public void user_verify_used_criticality() {
        tmp.verifyUsedCriticality(generateCriticality);
    }

    @Then("User verifies the record status")
    public void user_verify_record_status() {
        tmp.verifyStatus();
    }

    @Then("User changes the criticality status")
    public void user_changes_criticality_status() {
        tmp.changeCriticalityStatus();
    }

    @When("User adds a new field named {string} with type {string}")
    public void user_add_new_field(String name, String type) {
        tmp.createField(name, type);
    }

    @Then("User clicks on the {string} tab in high risk masters")
    public void userClicksOnTheTab(String tabTitle) {
        tmp.clickOnTabByTitle(tabTitle);
    }

    @Then("User checks the HW Number {string} should be autogenerated and read-only")
    public void verify_field_HwNo(String fieldName) {
        tmp.verifyAutogeneratedHWNo(fieldName);
    }

    @Then("User checks the Requested On {string} should be autogenerated and read-only")
    public void verify_field_RequestedOn(String fieldName) {
        tmp.verifyAutogeneratedRequestedOn(fieldName);
    }

//    @Then("User checks the Initiated By {string} should be autogenerated and read-only")
//    public void verify_field_InitiatedBy(String fieldName) {
//        tmp.verifyAutogeneratedInitiatedBy(fieldName);
//    }

//    @When("User selects value in the {string} dropdown")
//    public void user_selects_dropdown_and_options(String dropdownName) {
//        By field;
//        By options;
//        if (dropdownName.equalsIgnoreCase("Criticality")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlCriticality_Input");
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlCriticality_DropDown'] li");
//      }
//        else if (dropdownName.equalsIgnoreCase("High Risk Activity Type")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlHWType_Input");
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlHWType_DropDown'] li");
//        }
//        else if (dropdownName.equalsIgnoreCase("Property Owner / Customer")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlCustomer_Input");
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlCustomer_DropDown'] li");
//            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
//        }
//        else if (dropdownName.equalsIgnoreCase("Property / Contract")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlContract_Input");
//            elementUtils.click(field);
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlContract_DropDown'] li");
//
//        }
//        else if (dropdownName.equalsIgnoreCase("Requester Type")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlRequesterType_Input");
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlRequesterType_DropDown'] li");
//        }
//        else if (dropdownName.equalsIgnoreCase("Requested By")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlRequestedBy_Input");
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlRequestedBy_DropDown'] li");
//        }
//        else if (dropdownName.equalsIgnoreCase("Designated Manager")) {
//            field = By.id("ctl00_ContentPlaceHolder1_ddlResponsible_Input");
//            options = By.cssSelector("[id='ctl00_ContentPlaceHolder1_ddlResponsible_DropDown'] li");
//        }
//        else {
//            throw new IllegalArgumentException("Unknown dropdown name: " + dropdownName);
//        }
//
//        elementUtils.click(field);
//        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
//        By firstItem = By.xpath("(//ul[contains(@class,'rcbList')]/li[contains(@class,'rcbItem')])[1]");
//        elementUtils.waitForElementVisible(firstItem, 50);
//        helperUtils.clickRandomElement(options);
//
//    }
//    @When("User selects value in the {string} dropdown")
//    public void user_selects_dropdown(String dropdownName) {
//        HWMastersPage.selectRandomDropdownValue(dropdownName);
//    }
//    @When("User fills the dependent location fields")
//    public void fill_dependent_fields() {
//
//        switch (selectedLevel) {
//            case "Base Unit":
//                tmp.selectOption(tmp.dropDownProperty, "Property A");
//                tmp.selectOption(tmp.dropDownZone, "Zone 1");
//                tmp.selectOption(tmp.dropDownSubZone, "Sub 1");
//                tmp.selectOption(tmp.dropDownBaseUnit, "Unit 101");
//                break;
//
//            case "SubZone":
//                tmp.selectOption(tmp.dropDownProperty, "Property A");
//                tmp.selectOption(tmp.dropDownZone, "Zone 1");
//                tmp.selectOption(tmp.dropDownSubZone, "Sub 1");
//                break;
//
//            case "Zone":
//                tmp.selectOption(tmp.dropDownProperty, "Property A");
//                tmp.selectOption(tmp.dropDownZone, "Zone 1");
//                break;
//
//            case "Property":
//                tmp.selectOption(tmp.dropDownProperty, "Property A");
//                break;
//        }
//    }
}

