@AuditInspections
Feature: Audit Management Module Automation

#  /////////////////////// @AuditCategorySetup
  @AuditCategorySetup @Create
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Category Setup' in sidebar menu
    And User clicks on button 'Create Audit Category'
    And User select the '' ACS Audit Master Category dropdown
    And User Enters ACS Audit Category Name
    And User select the '' ACS Enforcing Authority dropdown
    And User select the '' ACS Industry Standard Description dropdown
    And User select the '' ACS Legal Requirements dropdown
    And User Enters Sampling Location and Asset Percentage
    And User select the '' ACS Work Order dropdown
    And User checks the Active check box in Create ACS
    When User clicking on Save Button in Schedules
    Then User verifies Audit Category Setup details in table

  @AuditCategorySetup @OpenAuditAddQuestion
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Category Setup' in sidebar menu
    And User clicks on First Created Audit to open
    And User clicks on Add Question Category
    When User clicking on Save Button in Schedules
    And User clicks on Add Question SubCategory
    When User clicking on Save Button in Schedules
    And User clicks on Add Question
    When User clicking on Save Button in Schedules

  @AuditCategorySetup @ErrorValidationMaxLength
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Category Setup' in sidebar menu
    And User clicks on button 'Create Audit Category'
    When User clicking on Save Button in Schedules
    When user verify the chars and max len as 100 for Audit Category
    Then user verify the inline error message 'Select Audit Master Category' on Audit Inspections
    Then user verify the inline error message 'Enter Audit Category' on Audit Inspections
    Then user verify the inline error message 'Select Enforcing Authority' on Audit Inspections
    Then user verify the inline error message 'Select Industry Standard Description' on Audit Inspections
    Then user verify the inline error message 'Select Legal & Other Requirements' on Audit Inspections
    Then user verify the inline error message 'Select Work Order Generation Type' on Audit Inspections














#  /////////////////////// @AuditSchedules
  @AuditSchedules @Create
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Schedules' in sidebar menu
    And User clicks on button 'Create audit schedule'
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_RadTxt_ScheduleNo' should be autogenerated and read-only
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_RadTxt_CreateDate' should be autogenerated and read-only
    And User select the '' Audit Master Category dropdown
    And User select the '' Audit Category dropdown
    Then User verify the Schedule Name details
    And User select the '' Client dropdown
    And User select the '' Client Category dropdown
    And User select the '' Property dropdown
    And User selects Check All for Applicable Zones
    And User select the '' Primary Auditee dropdown
    When User select the '' Schedule Start Date
    When User select the '' Schedule End Date
    And User select the '' Frequency dropdown
    And User select the '' Audit Company Type dropdown
    And User select the '' Auditor Designation dropdown
    When User clicking on Save Button in Schedules
    Then User verifies added Audit Schedule details in table

  @AuditSchedules @Edit
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Schedules' in sidebar menu
    And User select the '' Schedule No record to edit
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_RadTxt_ScheduleNo' should be autogenerated and read-only
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_RadTxt_CreateDate' should be autogenerated and read-only
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_AduitMC_Combo1_Input' should be autogenerated and read-only
    Then User verify the Scheduled name field
    And User select the '' Client dropdown
    And User select the '' Client Category dropdown
    And User select the '' Property dropdown
    And User selects Check All for Applicable Zones
    And User select the '' Primary Auditee dropdown
    When User select the '' Schedule Start Date
    When User select the '' Schedule End Date
    And User select the '' Frequency dropdown
    And User select the '' Audit Company Type dropdown
    And User select the '' Auditor Designation dropdown
    When User clicking on Save Button in Schedules
    Then User verifies added Audit Schedule details in table

  @AuditSchedules @Delete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Schedules' in sidebar menu
    Then User Select the page size 50
    And User select the Schedule No record to Delete
    When User clicks on available audit to delete
    Then User waits for 3 seconds
    Then User verify if the Audit Schedule record is deleted

  @AuditSchedules @ErrorValidationMaxLength
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Audit Schedules' in sidebar menu
    And User clicks on button 'Create audit schedule'
    And User clicks on Save button For Schedule InLine Error
    When user verify the chars and max len as 199 for Schedule Name
    Then user verify the inline error message 'Select Audit Master Category' on Audit Inspections
    Then user verify the inline error message 'Select Audit Category' on Audit Inspections
    Then user verify the inline error message 'Enter Schedule Name' on Audit Inspections
    Then user verify the inline error message 'Select Client' on Audit Inspections
    Then user verify the inline error message 'Select Client Contract' on Audit Inspections
    Then user verify the inline error message 'Select Property' on Audit Inspections
    Then user verify the inline error message 'Select Primary Auditee' on Audit Inspections
    Then user verify the inline error message 'Select Applicable Zones' on Audit Inspections
    And User select the 'Night Audits' Audit Master Category dropdown
    And User select the '' Audit Category dropdown
    Then User waits for 3 seconds
    And User select the 'Alpha Properties' Client dropdown
    And User select the 'ABC Tower' Client Category dropdown
    And User select the 'ABCD01' Property dropdown
    And User clicks on Save button For Schedule InLine Error
    Then user verify the inline error message 'Select Start Date' on Audit Inspections
    Then user verify the inline error message 'Select frequency' on Audit Inspections
    Then user verify the inline error message 'Select Audit Company Type' on Audit Inspections
    Then user verify the inline error message 'Select Designation' on Audit Inspections

# /////////////////////Create Unscheduled Audits
  @UnscheduledAudit @Create
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Create Unscheduled Audit' in sidebar menu
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_txtAuditNo' should be autogenerated and read-only
    Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_dtpAuditDate_dateInput' should be autogenerated and read-only
    And User select the '' UnSchedule Audit Master Category dropdown
    And User select the '' UnSchedule Audit Category dropdown
    Then User verify the Audit Name details
    And User select the '' US Client dropdown
    And User select the '' Client Category dropdown
    And User select the '' US Property dropdown
    And User select the '' Auditor Company dropdown
    And User select the '' Auditee dropdown
    And User select the '' Auditee StaffName dropdown
    And User select the '' Auditor dropdown
    When User clicking on Save Button in Schedules
    Then User waits for 3 seconds
    And User clicks on 'Assigned Audits' in sidebar menu
    Then User verifies added UnSchedule Audit details in table

  @UnscheduledAudit @ErrorValidationMaxLength
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Create Unscheduled Audit' in sidebar menu
    And User clicks on Save button For Schedule InLine Error
    When user verify the chars and max len as 200 for Audit Name
    Then user verify the inline error message 'Select Audit Master Category' on Audit Inspections
    Then user verify the inline error message 'Select Audit Category' on Audit Inspections
    Then user verify the inline error message 'Enter Audit Name' on Audit Inspections
    Then user verify the inline error message 'Select Client' on Audit Inspections
    Then user verify the inline error message 'Select Client Contract' on Audit Inspections
    Then user verify the inline error message 'Select Property' on Audit Inspections
    Then user verify the inline error message 'Select Applicable Zones' on Audit Inspections
    Then user verify the inline error message 'Select Auditor Company' on Audit Inspections
    Then user verify the inline error message 'Select Auditee' on Audit Inspections
    Then user verify the inline error message 'Select Auditor' on Audit Inspections
    Then user verify the inline error message 'Select Auditee Company' on Audit Inspections

#   ///////////////////////Assigned Audits
  @AssignedAudits @Delete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Assigned Audits' in sidebar menu
    Then User Select the page size 50
    And User select the US and Schedule Audit No record to Delete
    When User clicks on Assigned audits to delete
    Then User waits for 3 seconds
    Then User verify if the Deleted Assigned record is deleted

  @AssignedAudits @Reschedule
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Assigned Audits' in sidebar menu
    Then User Select the page size 50
    And User select the US and Schedule Audit No record to Reschedule
    When User clicks on Assigned audits to Reschedule
    When User clicking on Save Button in Schedules
    Then User verify if the Rescheduled date Assigned record is changed

#  /////////////////////Pending Assignments
  @PendingAssignments @Assign
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Pending Assignments' in sidebar menu
    Then User Select the page size 50
    And User select the Pending Assignments and Schedule Audit No record to Assign
    When User clicks on Schedule audits to Assign
    When User get All Assign Audit details
    And User selects Check All for Applicable Zones
    And User select the '' Auditor Company dropdown
    And User select the '' Auditee dropdown
    And User select the '' Auditee StaffName dropdown
    And User select the '' Auditor dropdown
    When User clicking on Save Button in Schedules
    Then User verifies Assigned details in Assigned Audits in table

#  /////////////////////Open Audits
#  ////UnAssigned
  @OAUnAssigned @UAAssign
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'UNASSIGNED' tab in Open Audits by Status
    Then User Select the page size 50 for 'UNASSIGNED' tab
#    /////////////////

  @OAUnAssigned @UADelete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'UNASSIGNED' tab in Open Audits by Status
    Then User Select the page size 50 for 'UNASSIGNED' tab
    And User select the OA and 'UNASSIGNED' Unassigned Schedule No record to Delete
    When User clicks on available audit to delete
    Then User waits for 3 seconds
    Then User verify if the UnAssigned record is deleted

  @OAUnAssigned @UAOpenAuditdetails
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'UNASSIGNED' tab in Open Audits by Status
    Then User Select the page size 50 for 'UNASSIGNED' tab
    And User select the OA and 'UNASSIGNED' Unassigned Schedule No record to Delete
    When User get the auditee details from table
    When User clicks on UnAssigned Schedule audits to open
    Then User verifies UnAssigned Schedule Audit Schedule details in table


#  ////OverDue
  @OAOverDue @ODTransfer
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'OVERDUE' tab in Open Audits by Status
    Then User Select the page size 50 for 'OVERDUE' tab
    And User select the OA and 'OVERDUE' Schedule No record to Delete
#    When User get the 'OVERDUE' auditee details from table
    When User clicks on 'OVERDUE' audit to Transfer
    And User select the Tranfer Auditor dropdown
    And User select the Reason dropdown and Remarks Text Save Tranfer
    When User clicking on Save Button in Schedules
    Then User verifies 'OVERDUE' Tranfer Audit Schedule details in table

  @OAOverDue @ODDelete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'OVERDUE' tab in Open Audits by Status
    Then User Select the page size 50 for 'OVERDUE' tab
    And User select the OA and 'OVERDUE' Schedule No record to Delete
    When User clicks on available audit to delete
    When User enter Audit Cancel details
    When User clicking on Save Button in Schedules
    When User clicks on 'OVERDUE' tab in Open Audits by Status
    Then User waits for 3 seconds
    Then User verify if the 'OVERDUE' record is deleted

  @OAOverDue @ODOpenAuditdetails
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'OVERDUE' tab in Open Audits by Status
    Then User Select the page size 50 for 'OVERDUE' tab
    And User select the OA and 'OVERDUE' Schedule No record to Delete
    When User get the 'OVERDUE' auditee details from table
    When User clicks on 'OVERDUE' Schedule audits to open
    Then User verifies OverDue Schedule Audit Schedule details in table


#  ////Upcoming
  @OAUnAssigned @UCODTransfer
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'UPCOMING' tab in Open Audits by Status
    Then User Select the page size 50 for 'UPCOMING' tab
    And User select the OA and 'UPCOMING' Schedule No record to Delete
#    When User get the 'UPCOMING' auditee details from table
    When User clicks on 'UPCOMING' audit to Transfer
    And User select the Tranfer Auditor dropdown
    And User select the Reason dropdown and Remarks Text Save Tranfer
    When User clicking on Save Button in Schedules
    Then User verifies 'UPCOMING' Tranfer Audit Schedule details in table

  @OAUnAssigned @UCDelete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'UPCOMING' tab in Open Audits by Status
    Then User Select the page size 50 for 'UPCOMING' tab
    And User select the OA and 'UPCOMING' Schedule No record to Delete
    When User clicks on available audit to delete
    When User enter Audit Cancel details
    When User clicking on Save Button in Schedules
    When User clicks on 'UPCOMING' tab in Open Audits by Status
    Then User waits for 3 seconds
    Then User verify if the 'UPCOMING' record is deleted

  @OAUnAssigned @UCOpenAuditdetails
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'UPCOMING' tab in Open Audits by Status
    Then User Select the page size 50 for 'UPCOMING' tab
    And User select the OA and 'UPCOMING' Schedule No record to Delete
    When User get the 'UPCOMING' auditee details from table
    When User clicks on 'UPCOMING' Schedule audits to open
    Then User verifies OverDue Schedule Audit Schedule details in table


#  ////InProgress
  @OAUnAssigned @IPDelete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'IN PROGRESS' tab in Open Audits by Status
    Then User Select the page size 50 for 'IN PROGRESS' tab
    And User select the OA and 'IN PROGRESS' Schedule No record to Delete
    Then User waits for 3 seconds
    When User clicks on available audit to delete
    When User enter Audit Cancel details
    When User clicking on Save Button in Schedules
    When User clicks on 'IN PROGRESS' tab in Open Audits by Status
    Then User waits for 3 seconds
    Then User verify if the 'IN PROGRESS' record is deleted

  @OAUnAssigned @IPOpenAuditdetails
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'IN PROGRESS' tab in Open Audits by Status
    Then User Select the page size 50 for 'IN PROGRESS' tab
    And User clicks on first available audit to open
    When User get the 'IN PROGRESS' auditee details from table
    When User clicks on 'IN PROGRESS' Schedule audits to open
    Then User verifies OverDue Schedule Audit Schedule details in table

#  ////All
  @OAUnAssigned @AllDelete
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'ALL' tab in Open Audits by Status
    Then User Select the page size 50 for 'ALL' tab
    And User select the OA and 'ALL' Schedule No record to Delete
    Then User waits for 3 seconds
    When User clicks on available audit to delete
    When User enter Audit Cancel details
    When User clicking on Save Button in Schedules
    When User clicks on 'ALL' tab in Open Audits by Status
    Then User waits for 3 seconds
    Then User verify if the 'ALL' record is deleted

  @OAUnAssigned @AllOpenAuditdetails
  Scenario: User Should be able to add it in AMC
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    When User clicks on 'Audit & Inspections Management' in navigation panel
    And User clicks on 'Open Audits' in sidebar menu
    When User clicks on 'ALL' tab in Open Audits by Status
    Then User Select the page size 50 for 'ALL' tab
    And User select the OA and 'ALL' Schedule No record to Delete
    When User get the 'ALL' auditee details from table
    When User clicks on 'ALL' Schedule audits to open
    Then User verifies OverDue Schedule Audit Schedule details in table









































