@HWMasters

Feature: High Risk Management Activities Automation

  @AddHighRiskActivitiesCriticality
  Scenario: Should be able to add High Risk Activities Criticality
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    Then User waits for 3 seconds
    And User clicks on 'Data Configurations' in navigation panel
    And User clicks on hamburger icon
    And User clicks on the 'High-Risk Activities Management' tab in data configuration page
    And User clicks on button 'Add'
    And User changes the criticality status
    And user fills up the criticality
    And User clicks on save button
    Then User waits for 3 seconds
    Then User verifies if the criticality is created or updated
    And User verifies the record status
    Then User waits for 10 seconds
    When User deletes the added record
    And User verifies if the criticality is deleted

  @EditHighRiskActivitiesCriticality
  Scenario: Should be able to edit High Risk Activities Criticality
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    Then User waits for 3 seconds
    And User clicks on 'Data Configurations' in navigation panel
    And User clicks on hamburger icon
    And User clicks on the 'High-Risk Activities Management' tab in data configuration page
    And User clicks on button 'Add'
    And user fills up the criticality
    And User clicks on save button
    And User waits for 3 seconds
    Then User verifies if the criticality is created or updated
    And User clicks on the criticality record
    And user fills up the criticality
    And User clicks on update button
    Then User verifies if the criticality is created or updated
    Then User attempts to delete the record and verifies the usage status
    And User waits for 10 seconds
    And User verifies if the criticality is deleted

  @DeleteHighRiskActivitiesCriticality
  Scenario: Should be able to delete High Risk Activities Criticality
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    Then User waits for 3 seconds
    And User clicks on 'Data Configurations' in navigation panel
    And User clicks on hamburger icon
    And User clicks on the 'High-Risk Activities Management' tab in data configuration page
    And User clicks on button 'Add'
    And user fills up the criticality
    And User clicks on save button
    And User waits for 3 seconds
    Then User verifies if the criticality is created or updated
    When User deletes the added record
    And User verifies if the criticality is deleted

  @CheckingMinMaxLengthAndErrorMessage
  Scenario: Should be able to delete High Risk Activities Criticality
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    Then User waits for 3 seconds
    And User clicks on 'Data Configurations' in navigation panel
    And User clicks on hamburger icon
    And User clicks on the 'High-Risk Activities Management' tab in data configuration page
    And User clicks on button 'Add'
    And user verifies the chars min len as 3 and max len as 100 on High Risk Criticality
    And User clicks on save button
    And user verifies the inline error message "Enter Hot Job / HW Criticality" on High Risk Criticality

  @AddHighRiskActivitiesFieldName
  Scenario: Should be able to add High Risk Activities Field Name
    Given User navigates to 'lattice.url' page
    When User is at home screen after login with "username" and "password"
    Then User waits for 3 seconds
    And User clicks on 'Data Configurations' in navigation panel
    And User clicks on hamburger icon
    And User clicks on the 'High-Risk Activities Management' tab in data configuration page
    And User clicks on the 'Assessment Fields' tab in high risk masters
    And User clicks on button 'Add'
    And User adds a new field named 'Installation Date' with type 'Date'
    And User clicks on save button

    @RegisterHighRiskActivity
    Scenario: Should be able to add High Risk Activities Field Name
      Given User navigates to 'lattice.url' page
      When User is at home screen after login with "username" and "password"
      Then User clicks on 'High-Risk Activities Management' in navigation panel
      Then User waits for 3 seconds
      Then User checks the HW Number 'radtxtHazardousNo' should be autogenerated and read-only
      Then User checks the Requested On 'ctl00_ContentPlaceHolder1_rdbRequestedDate_dateInput' should be autogenerated and read-only
      Then User checks the Initiated By 'ctl00_ContentPlaceHolder1_txtinitiatedby' should be autogenerated and read-only
      When User selects value in the "Criticality" dropdown
      When User selects value in the "High Risk Activity Type" dropdown
      #When User selects value in the "Property Owner / Customer" dropdown
      #When User selects value in the "Property / Contract" dropdown
      When User selects value in the "Requester Type" dropdown
      When User selects value in the "Requested By" dropdown
      When User selects value in the "Designated Manager" dropdown

